export const route = {
  home: "/",
  about: "about",
  login: "login",
  register: "register",
  profile: "profile",
  contact: "contact",
  shop: "shop",
  notfound: "not-found",
  perfumes: "perfumes",
  cart: "cart",
  orderHistory: "order-history",
  checkout: "checkout",
  ordersuccess: "order-successfully",
  orderfailed: "order-failed",
  ordertracking: "order-tracking",

  admin: "/admin",
  userManagement: "user-management",
  perfumeManagement: "perfume-management",
  brandManagement: "brand-management",
  eventManagement: "event-management",
  orderManagement: "order-management",
  warrantyManagement: "warranty-management",
  paymentManagement: "payment-management",

  shipper: "shipper",
  staff: "staff",
};
